// <auto-generated />
namespace Vista.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class borrar_campoEstado_de_imagen : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(borrar_campoEstado_de_imagen));
        
        string IMigrationMetadata.Id
        {
            get { return "201905280039152_borrar_campoEstado_de_imagen"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
